guard :rspec, cmd: 'bundle exec rspec' do
  watch(%r{^app/(.+)\.rb$})     { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^spec/(.+)\.json$})  { |m| "spec/#{m[1]}.rb" }
end

notification :tmux,
  change_color:           true,
  color_location:         'status-left-fg',
  display_message:        true,
  default_message_format: '%s: %s',
  default_message_color:  'brightblack'
