guard :rspec, cmd: 'bundle exec rspec' do
  watch(%r{^app/(.+)\.rb$})     { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^spec/.+_spec\.rb$})
end

notification :tmux,
  display_message:        true,
  default_message_format: '%s: %s',
  default_message_color:  'brightblack',
  change_color:           false
